### ISSUE TITLE
About installation 

### ISSUE THREAD

**Issue by Shinchan7222** [yohanesgultom/wapi#36]
Is it completed?

And can I use it with my shared hosting I have ssh access but I don't have root access I can also reserve ports

**Comment by yohanesgultom** [comment]
It is "as-is" 

It unlikely will work in shared hosting as `whatsapp-web.js` relies on `puppeteer` and `chromium`

**Comment by Shinchan7222** [comment]
> It is "as-is"
> 
> It unlikely will work in shared hosting as `whatsapp-web.js` relies on `puppeteer` and `chromium`

Yeah they are not supported on freeBSD
